persistentjabber: attempt to fix a race condition
The symptom is:
  AttributeError: 'NoneType' object has no attribute 'set_response_handlers'

The cause most likely is a race. So the scope of the client_lock is
widened. The lock is held by the run loop and only released for select.

Also turn the absence of the stream into a handled case.